### ISSUE TITLE
Not find Directory ~/.zsh in /Arbitrium-RAT/Clients/AndroidApp/

### ISSUE THREAD

**Issue by androidblack** [BenChaliah/Arbitrium-RAT#1]
Hi
I can't find ~/.zsh in /Arbitrium-RAT/Clients/AndroidApp/ address and cat it and source it and i product it with nano .
I 
![Untitled](https://user-images.githubusercontent.com/77880722/105622868-d1869580-5dc9-11eb-9f29-c19c8068f939.png)
can't execute make build 
my error is:
ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=all APP_PLATFORM=android-21
make: ndk-build: No such file or directory
make: *** [Makefile:8: build] Error 127

**Comment by BenChaliah** [comment]
the ~/.zsh file you saw I guess in the demo video is for Kali linux, I guess in your case it'll be ~/.bashrc, as for the settings those are different from one to another, the video only says that you should setup Android SDK, NDK, Oracle Java 1.8 and Gradle then you use ~/.bashrc (or ~/.zsh depends on distro) to set **env** variables.
p.s: I'm working on a primary version of Arbitrium CLI which will allows you to generate clients and deploy servers with few clicks, it'll come with a **Docker** image so no settings from your part are required
