### ISSUE TITLE
failing to create clients

### ISSUE THREAD

**Issue by Minecon724** [BenChaliah/Arbitrium-RAT#10]
windows > exe and linux > elf:
`Traceback (most recent call last):`
`File "main.py", line 362, in <module>`
`globals()[func_name](accu_settings)`
 `File "main.py", line 239, in _generateclients_windows__` (line 291 in linux elf)
`mv docker_assets/singleFrame.py docker_assets/{}.py".format(params['fqdn'], singleFrame))`
`IndexError: tuple index out of range`

everything else except android:
`Traceback (most recent call last):`
  `File "main.py", line 362, in <module>`
    `globals()[func_name](accu_settings)`
  `File "main.py", line 253, in _generateclients_windows__ ` (line 301 in linux)
    `sed -i s/{168.119.146.55}/{}/g output/Windows/singleFrame.py".format(params['fqdn']))`
`IndexError: tuple index out of range`

**Comment by BenChaliah** [comment]
After you opened this issue, I created a VM (ubuntu 18.04.5 but not necessarily bcz CLI uses docker) then I run exactly the following commands (as root):
```shell
$ apt update
$ git clone https://github.com/benchaliah/Arbitrium-RAT --recursive
$ cd Arbitrium-RAT/ArbitriumCLI/
$ apt install python-pip -y
$ pip2 install pyinquirer==1.0.3
$ python2.7 main.py
```
Then `Generate clients -> Windows -> [Enter] -> [Enter] -> Exe -> y -> [Enter]`
I didn't get the same error, can you make a MWE (minimal reproducible example)

**Comment by yoooby** [comment]
i'm having same error

**Comment by BenChaliah** [comment]
Did you follow the steps I suggested? if yes, can you please make a MWE (minimal reproducible example)

**Comment by Minecon724** [comment]
sorry for late reply
last time i was using this software was a week ago, however i managed to fix this error (by restarting/reinstalling), but there was another problem - this script was not connecting to server (console was clear, no errors) and the panel was loading very long
