### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by spiider75** [BenChaliah/Arbitrium-RAT#11]
Bonjour
en voulant compiler un client windows, j'ai ce message d'erreur
line 362, in <module>
    globals()[func_name](accu_settings)

Est ce normal ?
Mon ip client : 10.0.0.5 port 443
Mon ip RAT : 10.0.0.2

**Comment by BenChaliah** [comment]
Bonsoir, nn c'est pas normal, je doute que ce soit à cause d'un bug dans Arbitrium ms on sait jamais, en tt cas envoie-moi une capture d'écran de l'erreur pour que je puisse la reproduire

**Comment by GamingMineblox** [comment]
I got a fix,
When you clone the repo and are going to use the CLI, don't use the ``setAPI_FQDN.sh`` script
That fixed it for me

**Comment by BenChaliah** [comment]
@GamingMineblox you're correct, `setAPI_FQDN.sh` wasn't meant to change in CLI, I'll update it today to exclude CLI directory
