### ISSUE TITLE
No Output (CLI)

### ISSUE THREAD

**Issue by GamingMineblox** [BenChaliah/Arbitrium-RAT#13]
So I got the CLI to work but, it doesn't create any clients in the output folder.
There are no errors, no logs, and no output files.

FileZilla Folder (SFTP):
![image](https://user-images.githubusercontent.com/42892277/113157932-9aa28500-923b-11eb-9293-832bd696fe6a.png)

CLI Output (After Windows, Linux and Android builds):
![image](https://user-images.githubusercontent.com/42892277/113158267-ef460000-923b-11eb-89f7-be487052aacf.png)

**Comment by BenChaliah** [comment]
Add `input("")` in ligne 220, this will prevent the clearing of the shell after the creation attempt then take a screenshot of the output plz
![image](https://user-images.githubusercontent.com/43894468/113158635-4055f400-923c-11eb-954d-1f197dc83f88.png)

**Comment by GamingMineblox** [comment]
![image](https://user-images.githubusercontent.com/42892277/113159983-5912d980-923d-11eb-9217-8167add244d6.png)

weird... I didn't save anything in the /root/ folder

**Comment by BenChaliah** [comment]
the root directory here is inside the docker container, the error you have is `segmentation fault` when trying to put the executable inside a SFX archive, you can try to access the container manually and run `rar a -r -cfg ...` to see why the core was dumped

**Comment by GamingMineblox** [comment]
This is all I can catch before it spams the console with stuff (when I ^C it says: too many system links)

![image](https://user-images.githubusercontent.com/42892277/113161942-22d65980-923f-11eb-8234-be6f91bf7df0.png)

**Comment by GamingMineblox** [comment]
I've tried to reinstall the CLI but it still gives me the same error

**Comment by GamingMineblox** [comment]
Does anyone know how to fix this issue? I can't seem to fix it.

**Comment by m0rtyy** [comment]
I seem to have the same problem, but it seems to only be with the windows EXE. The python file works fine, if that helps.

**Comment by GamingMineblox** [comment]
> I seem to have the same problem, but it seems to only be with the windows EXE. The python file works fine, if that helps.

I'm going to try the python file now. 

Okay the Python file can build but, my home computer (What I am trying this on) doesn't support Python2.7 sadly.
I really need the EXE version as that is the only one that works on the PC I want to target (Home Family Desktop and yes my family knows).

**Comment by BenChaliah** [comment]
Yes ofc python version works, bcz the issue has nothing to do with Arbitrium but rather to `rar` binary and `sfx` creation which isn't involved in python format, I advise you to search why 
![image](https://user-images.githubusercontent.com/43894468/113508581-2163a480-9551-11eb-8998-8f42c1c41e0a.png)
gives you `segmentation fault`

**Comment by GamingMineblox** [comment]
> Yes ofc python version works, bcz the issue has nothing to do with Arbitrium but rather to `rar` binary and `sfx` creation which isn't involved in python format, I advise you to search why
> ![image](https://user-images.githubusercontent.com/43894468/113508581-2163a480-9551-11eb-8998-8f42c1c41e0a.png)
> gives you `segmentation fault`

I ran that command, and it gives me 2 errors (as I've shown before)

1. It can't find some programs (Java, OpenSSL, JVM, gcov, ZIP, p7ZIP, KRB5 inside the docker container)
2. It tries to create too many system links

**Comment by BenChaliah** [comment]
The real error is `segmentation fault` as for `not found` that probably happens because you run the command from a wrong path, therefore, you're trying to make an archive of the entire container instead of only the concerned files, the docker container run the following 
![image](https://user-images.githubusercontent.com/43894468/113509450-f62f8400-9555-11eb-87a6-030ab0e97c92.png)

means (if I recall correctly) you need to be inside `/root/build_assets/dist` before running `rar`

**Comment by GamingMineblox** [comment]
When I run ``rar a -r -cfg -sfxwindows.sfx -zSFXAutoInstaller.conf -XSFXAutoInstaller.conf WinApp.exe`` inside the ``/root/build_assets/dist/`` folder I only get an Segmentation fault (core dumped) error and nothing else.

![image](https://user-images.githubusercontent.com/42892277/113509610-d3ea3600-9556-11eb-9912-0708c7ec0195.png)

I don't really understand much from docker or rar

**Comment by BenChaliah** [comment]
I know that why I closed the issue and told you that your error has nothing to do with Arbitrium, anyway and alternative solution would be to copy the content of `dist` folder to your host OS (let say windows) and build SFX using winrar which can be easily done using GUI

> Yes ofc python version works, bcz the issue has nothing to do with Arbitrium but rather to `rar` binary and `sfx` creation which isn't involved in python format, I advise you to search why
> ![image](https://user-images.githubusercontent.com/43894468/113508581-2163a480-9551-11eb-8998-8f42c1c41e0a.png)
> gives you `segmentation fault`

**Comment by m0rtyy** [comment]
how would i copy the content of the dist folder? do you mean in the ArbitriumCLI folder? there's nothing there if that's the one you are talking about

**Comment by BenChaliah** [comment]
dist is a folder inside the docker container, to make sure the container is running try to generate EXE client, and after it gives you the error open a new terminal window without closing CLI, and now you can copy files from the running container as following; `docker cp arbitrium:/root/build_assets/dist .`

**Comment by m0rtyy** [comment]
Okay I followed the directions and I think it worked - I have a dist folder with this: 
![image](https://user-images.githubusercontent.com/81890973/113517715-52d77280-9547-11eb-8af0-5406bdfac40c.png)

**Comment by BenChaliah** [comment]
Yep now u only need the *.exe and *.vbs files, move them to a windows machine and build the SFX using winrar, the SFX must run the *.vbs after setup not the exe.

**Comment by BenChaliah** [comment]
I'm curious though, to build the client were you using x86 or x64?

**Comment by m0rtyy** [comment]
Well I'm on a x64 linux using CLI, and I am going to move it to a x64 windows 10 machine

**Comment by GamingMineblox** [comment]
> I'm curious though, to build the client were you using x86 or x64?

on a x64 bits computer.

**Comment by m0rtyy** [comment]
I'm confused, what do I do from here? 
![image](https://user-images.githubusercontent.com/81890973/113525135-d78eb480-9578-11eb-90f7-b8e52ac4b600.png)
