### ISSUE TITLE
runFrame.py and WebApp 

### ISSUE THREAD

**Issue by GamingMineblox** [BenChaliah/Arbitrium-RAT#6]
Hello again, so I managed to setup the webapp on a local network
It works but i had 2 questions

1. How do I let standalone.exe unzip runframe.exe in a custom location (not user changable) and make it run in the background when the device boots?

2. How do I fix this error when I press dump credentials
![image](https://user-images.githubusercontent.com/42892277/110221241-630a1c80-7ecb-11eb-915f-694e62c13141.png)

**Comment by BenChaliah** [comment]
- 1 - For you first question I'd refer you to [SFXAutoInstaller.conf](https://github.com/BenChaliah/Arbitrium-RAT/blob/main/Clients/WindowsApp/Client_tools/SFXAutoInstaller.conf), you can set `InstallPath="path_that_you_want"`, you can also extract __runFrame.exe__ (by selecting extract after right click if you're on windows), then build another SFX file, you can use Winrar or 7z SFX Builder, both have an easy GUI, you can change icon, and many configurations.

- 2 - it look like you don't have `python` command in the server where _serverAPI_ is deployed, try running python in the shell of your server to check, if python is installed but you must run python3 for instance to run it then you can create a symbolic link to `/usr/bin/python` using `ln -s`

**Comment by GamingMineblox** [comment]
Okay thank you for the support :D

When I made the symbolic link to python3 it didn't give me that error.
![image](https://user-images.githubusercontent.com/42892277/110222925-5ccd6d80-7ed6-11eb-8ea9-9a7a7442ee8f.png)

**Comment by BenChaliah** [comment]
You can either change in modules so they can work with python3 or make the symbolic link to python2.7 (the latest is the recommended solution), make sure you have python2.7 installed

**Comment by GamingMineblox** [comment]
For some reason the runFrame.exe is now getting detected by Windows Defender (Our school has it force-enabled so I can't just disable that)
