### ISSUE TITLE
runFrame.exe crash & toolbox.exe virus

### ISSUE THREAD

**Issue by GamingMineblox** [BenChaliah/Arbitrium-RAT#8]
Hey again 👋 

So the web-app works, it shows all devices with the runFrame.exe on the main page.
But when I try to run action from the web panel the runFrame.exe will crash instantly.
I haven't been able to catch the error as it closes in a split second.

Second part of the issue
When I try the credential dump (even when the runFrame.exe crashes) Windows Defender will give a notification that there is a virus detected and placed in quarantine. The virus that was detected was the toolbox.exe. When I go and look in the installation path where the toolbox should be located it isn't there. I even tried downloading it from this repo, but it gave me a virus notification and blocked the download. On the laptop I'm trying to run this on it also gives me a virus warning when I try to build the project with WinRAR (Rar.exe x86 bits).

If you can catch the error code from runFrame.exe I will post it here (after I try to fix it myself)

For the toolbox.exe. I don't know how I would fix this as I don't have access to the Windows Defender smart screen. (Family restrictions)

**Comment by GamingMineblox** [comment]
I wasa able to get the error the runFrame.exe was producing

It is caused by the toolbox.exe not being accessible / deleted. (See picture at bottom)
So the problem is. How do I hide toolbox.exe from Windows Defender. Because the antivirus keeps deleting the toolbox.exe, and I am unable to disable the antivirus myself. And the family administrator won't disable it because he is very careful and doesn't want a virus on his network (I am making this as a prank for my friends. I am not doing anything major or illegal with it).

runFrame.exe crash error:
![image](https://user-images.githubusercontent.com/42892277/110255063-3a992580-7f92-11eb-8e07-ceb462b333d7.png)

Web action error:
![image](https://user-images.githubusercontent.com/42892277/110255084-51d81300-7f92-11eb-92e2-ff7f73d51111.png)

**Comment by GamingMineblox** [comment]
@BenChaliah Could you release the source code for the toolbox.exe (If that's possible) I want to try and bypass windows defender

**Comment by BenChaliah** [comment]
Try the CLI I just released, the clients it generate don't have the toolbox attached
