### ISSUE TITLE
Can't login to web interface

### ISSUE THREAD

**Issue by Aoxomoxoa** [BenChaliah/Arbitrium-RAT#9]
Hi!
trying to configure Arbitrum-RAT and log in to the web interface, but the login does not work. See all this error in console 
![screen](https://user-images.githubusercontent.com/1074971/111463326-81c0ac80-8730-11eb-94aa-6c1e3cc209a4.png)

How can I fix all of this errors?
And why web script try to send request to 80 port (which results in a cors violation error)?

**Comment by BenChaliah** [comment]
this usually (but not always) happend because of using python3 to run the server, you need to check the headers in the HTTP response of the server. A simple solution is to use the CLI which will setup inside a docker container the proper libraries, versions ...etc
